site_name: Hellas Direct
site_url: https://hellasdirect.github.io
# Location of md files.
docs_dir: mkdocs
# Build directory.
site_dir: docs
plugins:
  - search
theme:
  logo: assets/logo.png
  favicon: assets/favicon.svg
  name: material
  locale: en
  language: en
  palette:
    primary: white
    scheme: slate
  features:
    - content.code.copy
# Syntax Highlighting:
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details