site_name: Hellas Direct
site_url: https://hellasdirect.github.io
docs_dir: mkdocs
site_dir: docs
plugins:
  - search
theme:
  logo: assets/logo.png
  favicon: assets/favicon.svg
  name: material
  locale: en
  language: en
  palette:
    primary: white
    scheme: slate
